### ISSUE TITLE
TODO because it really starts to be annoying

### ISSUE THREAD

**Issue by BDonnot** [BDonnot/ChroniX2Grid#74]
- [ ] remove the tons of packages required in the setup.py
- [ ] remove the super annoying print everywhere
- [ ] clean the "deprecation" issued by pandas and numpy
